const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { chromium } = require(path.join(process.env.PLAYWRIGHT_TOOLS, 'node_modules/playwright'));
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--no-proxy-server', '--host-resolver-rules=MAP panel.test 127.0.0.1'] });
  const base = process.env.FIREWALL_UI_BROWSER_URL || 'http://panel.test:18123';
  const output = process.env.FIREWALL_UI_SCREENSHOTS || '/tmp/firewall-ui-ui-shots';
  fs.mkdirSync(output, { recursive: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies([{ name: 'firewall_ui_session', value: 'obsolete-secure-cookie', domain: new URL(base).hostname, path: '/', secure: true, httpOnly: true, sameSite: 'Strict' }]);
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  async function signIn(target) {
    await target.getByLabel('Имя пользователя', { exact: true }).fill('admin');
    await target.getByLabel('Пароль', { exact: true }).fill('1');
    await target.getByRole('button', { name: 'Войти', exact: true }).click();
  }
  await page.goto(base);
  await page.getByRole('button', { name: 'Войти', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), 'cyberpunk');
  await page.screenshot({ path: path.join(output, 'login.png') });
  await signIn(page);
  await page.locator('.page-header').waitFor();
  await page.locator('.dashboard-stat').first().waitFor();
  assert.equal(await page.evaluate(async () => (await fetch('/api/session')).status), 200);
  await page.screenshot({ path: path.join(output, 'overview-desktop.png'), fullPage: true });
  await page.getByRole('menuitem', { name: 'Настройки' }).click();
  await page.getByRole('button', { name: 'Сохранить настройки' }).waitFor();
  assert.equal(await page.locator('input[type=file]').evaluate(input => getComputedStyle(input).display), 'none');
  await page.screenshot({ path: path.join(output, 'settings-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile layout overflows');
  await page.screenshot({ path: path.join(output, 'settings-mobile.png'), fullPage: true });
  // Exercise compact rules and deletion against isolated API fixtures.
  await page.setViewportSize({ width: 1440, height: 1000 });
  let manual = ['tcp', 'udp'].map(protocol => ({ port: 9000, protocol, label: 'paired manual' }));
  let advanced = ['tcp', 'udp'].map(protocol => ({ id: `paired-${protocol}`, protocol, action: 'allow', portStart: 9001, portEnd: 9002, sourceCidr: '', interface: '', ipVersion: 'any', priority: 100, label: 'paired advanced' }));
  const requests = [];
  const status = () => ({ supported: true, backend: 'ufw', enabled: true, autoSync: false, pingEnabled: true,
    rules: manual.map(rule => ({ ...rule, source: 'manual', owned: true, exists: true })), manualRules: manual });
  const response = (route, obj) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true, obj, msg: '' }) });
  await page.route('**/panel/api/server/firewall/status', route => response(route, status()));
  await page.route('**/api/firewall/advanced', route => response(route, advanced));
  await page.route('**/panel/api/server/firewall/rules/delete', route => {
    const data = route.request().postDataJSON(); requests.push(data);
    manual = manual.filter(rule => rule.port !== data.port || rule.protocol !== data.protocol);
    return response(route, status());
  });
  await page.route('**/api/firewall/advanced/delete', route => {
    const data = route.request().postDataJSON(); requests.push(data);
    advanced = advanced.filter(rule => rule.id !== data.id);
    return response(route, { rules: advanced });
  });
  await page.getByRole('menuitem', { name: 'Файрволл' }).click();
  const manualCard = page.locator('.ant-card').filter({ has: page.getByText('Простые ручные правила', { exact: true }) });
  const advancedCard = page.locator('.ant-card').filter({ has: page.getByText('Расширенные правила', { exact: true }) });
  await manualCard.getByText('TCP / UDP', { exact: true }).waitFor();
  await advancedCard.getByText('TCP / UDP', { exact: true }).waitFor();
  assert.equal(await manualCard.getByRole('button', { name: 'Удалить', exact: true }).count(), 0);
  await manualCard.locator('.ant-table-row-expand-icon-collapsed').click();
  await advancedCard.locator('.ant-table-row-expand-icon-collapsed').click();
  await page.screenshot({ path: path.join(output, 'paired-rules-desktop.png'), fullPage: true });
  const manualTCP = manualCard.locator('.ant-table-expanded-row .ant-table-row').filter({ has: page.getByText('TCP', { exact: true }) });
  await manualTCP.getByRole('button', { name: 'Удалить', exact: true }).click();
  await page.locator('.ant-popconfirm').getByRole('button', { name: /OK|Да|ОК/ }).click();
  await manualCard.getByText('UDP', { exact: true }).waitFor();
  assert.deepEqual(requests[0], { port: 9000, protocol: 'tcp' });
  assert.equal(await manualCard.getByText('TCP / UDP', { exact: true }).count(), 0);
  const advancedTCP = advancedCard.locator('.ant-table-expanded-row .ant-table-row').filter({ has: page.getByText('TCP', { exact: true }) });
  await advancedTCP.getByRole('button', { name: 'Удалить', exact: true }).click();
  await page.locator('.ant-popconfirm').getByRole('button', { name: /OK|Да|ОК/ }).click();
  await advancedCard.getByText('UDP', { exact: true }).waitFor();
  assert.deepEqual(requests[1], { id: 'paired-tcp' });
  assert.deepEqual(advanced.map(rule => rule.id), ['paired-udp']);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Rules mobile layout overflows');
  await page.screenshot({ path: path.join(output, 'paired-rules-mobile.png'), fullPage: true });
  assert.deepEqual(errors, []);
  // The login response alone must never mount protected pages without a cookie.
  const blocked = await browser.newContext();
  const blockedPage = await blocked.newPage();
  await blockedPage.route('**/api/login', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true, obj: { csrf: 'fixture' }, msg: '' }) }));
  await blockedPage.goto(base);
  await signIn(blockedPage);
  await blockedPage.getByText(/Браузер не сохранил сессию/).waitFor();
  assert.equal(await blockedPage.locator('.page-header').count(), 0);
  await browser.close();
  console.log('Browser login/session, cookie rejection, protocol-specific deletion and cyberpunk desktop/mobile checks passed');
})().catch(error => { console.error(error); process.exit(1); });
