package service

import (
	"context"
	"errors"
	"fmt"
	"os/exec"
	"strings"
)

// CleanupOwnedRules removes panel policy without disabling the system firewall.
// The caller must stop the service first to prevent automatic reconciliation.
func (s *FirewallService) CleanupOwnedRules(ctx context.Context) error {
	firewallMu.Lock()
	defer firewallMu.Unlock()
	if binary, err := exec.LookPath("ufw"); err == nil {
		text, err := runFirewallCommand(ctx, binary, "show", "added")
		if err != nil {
			return err
		}
		for _, line := range strings.Split(text, "\n") {
			args := ownedUFWDeleteArgs(line)
			if args == nil {
				continue
			}
			if _, err := runFirewallCommand(ctx, binary, args...); err != nil {
				return err
			}
		}
	}
	if backend, err := detectFirewallBackend(ctx); err == nil && backend.name == "firewalld" {
		if err := removeManagedLegacyRules(ctx, backend); err != nil {
			return err
		}
		advanced, err := loadAdvancedFirewallRules()
		if err != nil {
			return err
		}
		for _, rule := range advanced {
			if err := removeFirewalldRichRule(ctx, backend, firewalldRichRule(rule)); err != nil {
				return err
			}
		}
	}
	if binary, err := exec.LookPath("nft"); err == nil {
		tables, err := runFirewallCommand(ctx, binary, "list", "tables")
		if err != nil && !unsupportedFirewallKernel(err) {
			return err
		}
		if err == nil && firewallOutputHasFields(tables, "table", "inet", managedNftTable) {
			if _, err := runFirewallCommand(ctx, binary, "delete", "table", "inet", managedNftTable); err != nil {
				return err
			}
		}
	}
	for _, name := range []string{"iptables", "ip6tables"} {
		binary, err := exec.LookPath(name)
		if err != nil {
			continue
		}
		rules, err := runFirewallCommand(ctx, binary, "-S")
		if err != nil {
			if unsupportedFirewallKernel(err) {
				continue
			}
			return err
		}
		if !firewallOutputHasFields(rules, "-N", managedIPTablesChain) {
			continue
		}
		for attempts := 0; ; attempts++ {
			if _, err := runFirewallCommand(ctx, binary, "-C", "INPUT", "-j", managedIPTablesChain); err != nil {
				break
			}
			if attempts >= 128 {
				return fmt.Errorf("too many managed jumps in %s", name)
			}
			if _, err := runFirewallCommand(ctx, binary, "-D", "INPUT", "-j", managedIPTablesChain); err != nil {
				return err
			}
		}
		if _, err := runFirewallCommand(ctx, binary, "-F", managedIPTablesChain); err != nil {
			return err
		}
		if _, err := runFirewallCommand(ctx, binary, "-X", managedIPTablesChain); err != nil {
			return err
		}
	}
	if err := saveFirewallJSON(firewallManagedRulesKey, []FirewallRule{}); err != nil {
		return err
	}
	return setFirewallManagedEnabledPreference(false)
}

// Command output is trimmed by runFirewallCommand. Match complete tokenized
// lines so the final (or only) table/chain is still found, without prefix matches.
func firewallOutputHasFields(output string, want ...string) bool {
	for _, line := range strings.Split(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) != len(want) {
			continue
		}
		match := true
		for i := range want {
			if fields[i] != want[i] {
				match = false
				break
			}
		}
		if match {
			return true
		}
	}
	return false
}

// A kernel without this family/backend cannot contain its managed rules.
// Permission errors, lock failures and unknown failures still abort cleanup.
func unsupportedFirewallKernel(err error) bool {
	message := strings.ToLower(err.Error())
	for _, reason := range []string{
		"address family not supported by protocol",
		"protocol not supported",
		"table does not exist (do you need to insmod?)",
	} {
		if strings.Contains(message, reason) {
			return true
		}
	}
	return false
}

// show added works even when UFW is inactive. Parse only the commands and exact
// ownership comments generated by this project; never pass text to a shell.
func ownedUFWDeleteArgs(line string) []string {
	line = strings.TrimSpace(line)
	before, comment, ok := strings.Cut(line, " comment ")
	if !ok || len(comment) < 2 {
		return nil
	}
	quote := comment[0]
	if (quote != '\'' && quote != '"') || comment[len(comment)-1] != quote {
		return nil
	}
	comment = comment[1 : len(comment)-1]
	owned := comment == "Firewall-UI managed" || comment == "Firewall-UI access"
	if strings.HasPrefix(comment, "Firewall-UI advanced ") {
		id := strings.TrimPrefix(comment, "Firewall-UI advanced ")
		owned = id != "" && strings.IndexFunc(id, func(r rune) bool {
			return !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-')
		}) == -1
	}
	fields := strings.Fields(before)
	if !owned || len(fields) < 3 || fields[0] != "ufw" || (fields[1] != "allow" && fields[1] != "deny" && fields[1] != "reject" && fields[1] != "limit") {
		return nil
	}
	for _, field := range fields[2:] {
		if strings.HasPrefix(field, "-") || strings.ContainsAny(field, "'\";\\$`\n\r") {
			return nil
		}
	}
	args := append([]string{"--force", "delete"}, fields[1:]...)
	return append(args, "comment", comment)
}

func removeFirewalldRichRule(ctx context.Context, backend firewallBackend, rich string) error {
	on, _ := backend.enabled(ctx)
	for _, permanent := range []bool{true, false} {
		command := backend.binary
		args := []string{"--zone=" + backend.zone}
		if !on {
			if !permanent {
				continue
			}
			command = backend.offline
			if command == "" {
				return fmt.Errorf("firewall-offline-cmd is required for cleanup")
			}
		} else if permanent {
			args = append(args, "--permanent")
		}
		if _, err := runFirewallCommand(ctx, command, append(args, "--query-rich-rule="+rich)...); err != nil {
			var exitErr *exec.ExitError
			if errors.As(err, &exitErr) && exitErr.ExitCode() == 1 {
				continue
			}
			return err
		}
		if _, err := runFirewallCommand(ctx, command, append(args, "--remove-rich-rule="+rich)...); err != nil {
			return err
		}
	}
	return nil
}
